# Generated by Django 5.2.17 on 2026-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_via',
            field=models.CharField(choices=[('manual', 'Manual'), ('easy_apply', 'Easy Apply')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='match_snapshot',
            field=models.JSONField(blank=True, help_text='Compact ATS match analysis captured when the application was submitted/analyzed.', null=True),
        ),
    ]
