# Generated by Django 5.2.17 on 2026-09-20 08:38

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_applied_via_application_match_snapshot'),
        ('jobs', '0002_job_application_method_job_badges_job_benefits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='match_snapshot',
        ),
        migrations.AddField(
            model_name='application',
            name='current_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='current_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='education_summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='github_url',
            field=models.URLField(blank=True, max_length=300, validators=[core.validators.validate_profile_url]),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300, validators=[core.validators.validate_profile_url]),
        ),
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=300, validators=[core.validators.validate_profile_url]),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated skills', max_length=500),
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired')], max_length=20)),
                ('new_status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_answers', to='applications.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobs.screeningquestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application', 'question'), name='unique_answer_per_question')],
            },
        ),
    ]
