# Generated by Django 5.2.17 on 2026-09-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_match_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_skills_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='match_percentage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Null means the job had no required skills to match against.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='student_skills_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='unmatched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
