# Generated by Django 5.2.17 on 2026-09-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_job_skills_snapshot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScreeningAnswer',
        ),
    ]
