# Generated by Django 5.2.17 on 2026-09-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_ats_breakdown_application_ats_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='new_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('hired', 'Hired'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('hired', 'Hired'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
