# Generated by Django 5.2.17 on 2026-09-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_method',
            field=models.CharField(choices=[('easy_apply', 'Easy Apply only'), ('apply', 'Apply only'), ('both', 'Both Easy Apply and Apply')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='badges',
            field=models.CharField(blank=True, help_text='Comma-separated badge keys, e.g. urgent_hiring,remote', max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education_required',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th / Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('doctorate', 'Doctorate')], max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20),
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='jobs.job')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
