# Generated by Django 5.2.17 on 2026-09-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_delete_screeninganswer'),
        ('jobs', '0004_seed_domains_backfill_jobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScreeningQuestion',
        ),
    ]
