# Generated by Django 5.2.17 on 2026-09-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_delete_screeningquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='preferred_skills',
            field=models.CharField(blank=True, help_text='Comma-separated preferred (nice-to-have) skills', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated required skills', max_length=500),
        ),
    ]
