# Generated by Django 5.2.17 on 2026-09-24 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_file_hash_resume_parse_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescan',
            name='analyzer_version',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='ATSIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('severity', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], max_length=10)),
                ('section', models.CharField(blank=True, max_length=30)),
                ('text', models.TextField(blank=True, help_text='The affected quoted text, if this issue is anchored to a span.')),
                ('start_position', models.PositiveIntegerField(blank=True, null=True)),
                ('end_position', models.PositiveIntegerField(blank=True, null=True)),
                ('page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=300)),
                ('suggestion', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('ignored', 'Ignored')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_issues', to='resumes.resume')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_issues', to='resumes.resumescan')),
            ],
            options={
                'ordering': ['severity', '-created_at'],
                'indexes': [models.Index(fields=['resume', 'status'], name='resumes_ats_resume__fed7bb_idx')],
            },
        ),
    ]
