# Generated by Django 5.2.17 on 2026-09-15 18:28

import core.utils
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer')], default='job_seeker', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('headline', models.CharField(blank=True, max_length=150)),
                ('summary', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills', max_length=500)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('profile_photos'), validators=[core.validators.validate_image_file])),
                ('resume', models.FileField(blank=True, null=True, upload_to=core.utils.UploadTo('resumes'), validators=[core.validators.validate_resume_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
