# Generated by Django 5.2.17 on 2026-09-17 07:35

import core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, max_length=300, validators=[functools.partial(core.validators.validate_profile_url, *(), **{'kind': 'github'})]),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300, validators=[functools.partial(core.validators.validate_profile_url, *(), **{'kind': 'linkedin'})]),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=300, validators=[core.validators.validate_profile_url]),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, max_length=300, validators=[core.validators.validate_profile_url]),
        ),
    ]
