# Generated by Django 5.2.17 on 2026-09-19 15:48

import core.utils
import core.validators
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_github_url_profile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CareerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_job_title', models.CharField(blank=True, max_length=150)),
                ('preferred_role', models.CharField(blank=True, max_length=150)),
                ('preferred_industry', models.CharField(blank=True, max_length=150)),
                ('preferred_department', models.CharField(blank=True, max_length=150)),
                ('preferred_location', models.CharField(blank=True, max_length=120)),
                ('work_mode', models.CharField(blank=True, choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('junior', '0-2 years'), ('mid', '2-5 years'), ('senior', '5-10 years'), ('lead', '10+ years')], max_length=20)),
                ('expected_salary', models.PositiveIntegerField(blank=True, help_text='Annual, in your local currency', null=True)),
                ('notice_period', models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('60_days', '60 Days'), ('90_days', '90 Days')], max_length=20)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('preferred_shift', models.CharField(blank=True, choices=[('day', 'Day'), ('night', 'Night'), ('flexible', 'Flexible')], max_length=20)),
                ('preferred_company_type', models.CharField(blank=True, choices=[('startup', 'Startup'), ('mnc', 'MNC'), ('product', 'Product-based'), ('service', 'Service-based'), ('any', 'Any')], max_length=20)),
                ('job_search_status', models.CharField(choices=[('actively_looking', 'Actively looking'), ('open_to_opportunities', 'Open to opportunities'), ('not_looking', 'Not looking')], default='open_to_opportunities', max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_preference', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills', max_length=500)),
                ('certificate', models.FileField(blank=True, null=True, upload_to=core.utils.UploadTo('internship_certificates'), validators=[core.validators.validate_resume_file])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated technologies', max_length=300)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True, max_length=300, validators=[core.validators.validate_profile_url])),
                ('github_url', models.URLField(blank=True, max_length=300, validators=[functools.partial(core.validators.validate_profile_url, *(), **{'kind': 'github'})])),
                ('team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('certification', 'Certification'), ('award', 'Award'), ('publication', 'Publication'), ('hackathon', 'Hackathon'), ('competition', 'Competition'), ('course', 'Course'), ('extracurricular', 'Extracurricular'), ('other', 'Other')], default='certification', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=300, validators=[core.validators.validate_profile_url])),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishments', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', '-date'],
                'indexes': [models.Index(fields=['profile', 'category'], name='accounts_ac_profile_26f315_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('proficiency', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_skills', to='accounts.profile')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
                'indexes': [models.Index(fields=['profile', 'is_primary'], name='accounts_ca_profile_806a89_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'name'), name='unique_skill_per_profile')],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th / Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('doctorate', 'Doctorate')], max_length=20)),
                ('degree', models.CharField(max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('grade', models.CharField(blank=True, help_text='CGPA or percentage', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', '-end_year', '-start_year'],
                'indexes': [models.Index(fields=['profile', 'order'], name='accounts_ed_profile_32cee1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('proficiency', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('fluent', 'Fluent'), ('native', 'Native')], default='intermediate', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='accounts.profile')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'name'), name='unique_language_per_profile')],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('skills_used', models.CharField(blank=True, help_text='Comma-separated skills', max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_records', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', '-is_current', '-start_date'],
                'indexes': [models.Index(fields=['profile', 'is_current'], name='accounts_wo_profile_5eb047_idx')],
            },
        ),
    ]
