# Generated by Django 5.2.17 on 2026-09-20 08:38

import core.utils
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_last_activity_at_and_more'),
        ('companies', '0002_company_benefits_company_business_proof_and_more'),
        ('jobs', '0002_job_application_method_job_badges_job_benefits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=300)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('experience_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=20)),
                ('work_mode', models.CharField(blank=True, choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20)),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_alerts', to='jobs.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('professional_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('recruitment_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('specialization', models.CharField(blank=True, choices=[('it', 'IT'), ('software', 'Software'), ('engineering', 'Engineering'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('education', 'Education'), ('bpo', 'BPO'), ('logistics', 'Logistics'), ('other', 'Other')], max_length=20)),
                ('roles_hiring_for', models.CharField(blank=True, help_text='Comma-separated roles', max_length=500)),
                ('hiring_domains', models.CharField(blank=True, help_text='Comma-separated domains', max_length=500)),
                ('candidate_experience_pref', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('junior', '0-2 years'), ('mid', '2-5 years'), ('senior', '5-10 years'), ('lead', '10+ years')], max_length=20)),
                ('hiring_locations', models.CharField(blank=True, help_text='Comma-separated locations', max_length=500)),
                ('salary_range_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_range_max', models.PositiveIntegerField(blank=True, null=True)),
                ('employment_types_hiring', models.CharField(blank=True, help_text='Comma-separated employment types', max_length=200)),
                ('remote_hiring', models.BooleanField(default=False)),
                ('freshers_hiring', models.BooleanField(default=False)),
                ('urgent_hiring', models.BooleanField(default=False)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('official_company_email', models.EmailField(blank=True, max_length=254)),
                ('employee_id', models.CharField(blank=True, max_length=60)),
                ('recruiter_role', models.CharField(blank=True, max_length=100)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to=core.utils.UploadTo('recruiter_verification'), validators=[core.validators.validate_resume_file])),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified')], default='unverified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiters', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('notify_job_alerts', models.BooleanField(default=True)),
                ('notify_application_updates', models.BooleanField(default=True)),
                ('notify_recruiter_updates', models.BooleanField(default=True)),
                ('notify_company_updates', models.BooleanField(default=True)),
                ('notify_interview_reminders', models.BooleanField(default=True)),
                ('notify_system', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('recruiters_only', 'Recruiters Only'), ('private', 'Private')], default='recruiters_only', max_length=20)),
                ('recruiters_can_view_profile', models.BooleanField(default=True)),
                ('recruiters_can_download_resume', models.BooleanField(default=True)),
                ('recruiters_can_contact', models.BooleanField(default=True)),
                ('show_in_recruiter_search', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='google', max_length=20)),
                ('provider_user_id', models.CharField(help_text="Stable subject id from the provider (e.g. Google 'sub').", max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_social_identity')],
            },
        ),
    ]
