# Generated by Django 5.2.17 on 2026-09-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpreference',
            name='job_search_status',
            field=models.CharField(blank=True, choices=[('actively_looking', 'Actively looking'), ('open_to_opportunities', 'Open to opportunities'), ('not_looking', 'Not looking')], default='open_to_opportunities', max_length=25),
        ),
        migrations.AlterField(
            model_name='careerpreference',
            name='willing_to_relocate',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
