# Generated by Django 5.2.17 on 2026-09-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_careerpreference_job_search_status_and_more'),
        ('jobs', '0005_delete_screeningquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobalert',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_alerts', to='jobs.jobdomain'),
        ),
    ]
