# Generated by Django 5.2.17 on 2026-09-22 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_application_job_skills_snapshot_and_more'),
        ('companies', '0003_companyoffice_contact_email_and_more'),
        ('jobs', '0003_jobdomain_job_domain_jobsubdomain_job_subdomain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('profile_view', 'Profile View'), ('search_appearance', 'Search Appearance'), ('resume_view', 'Resume View'), ('resume_download', 'Resume Download'), ('shortlisted', 'Shortlisted'), ('contacted', 'Contacted'), ('interview', 'Interview'), ('application_status', 'Application Status Update'), ('profile_update', 'Profile Update')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='applications.application')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'student activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='activity_st_student_2d80f4_idx'), models.Index(fields=['student', 'event_type'], name='activity_st_student_4cc093_idx'), models.Index(fields=['company', 'event_type'], name='activity_st_company_76620f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('candidate_search', 'Candidate Search'), ('application', 'Application'), ('direct', 'Direct')], default='direct', max_length=20)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.company')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['student', '-viewed_at'], name='activity_st_student_eafd3f_idx'), models.Index(fields=['recruiter', 'student'], name='activity_st_recruit_6924d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentSearchAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.company')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_appearances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='activity_st_student_18fffa_idx'), models.Index(fields=['recruiter', 'student'], name='activity_st_recruit_88afbe_idx')],
            },
        ),
    ]
