# Generated by Django 5.2.17 on 2026-09-15 18:28

import core.utils
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, help_text='e.g. 11-50 employees', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('company_logos'), validators=[core.validators.validate_image_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
    ]
