# Generated by Django 5.2.17 on 2026-09-20 08:38

import core.utils
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='business_proof',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.UploadTo('company_verification'), validators=[core.validators.validate_resume_file]),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('startup', 'Startup'), ('mnc', 'MNC'), ('product', 'Product-based'), ('service', 'Service-based'), ('any', 'Any')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('company_covers'), validators=[core.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='company',
            name='culture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='company',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='official_domain',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='official_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='services_offered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma-separated technologies', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='work_environment',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CompanyOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('branch', 'Branch')], default='branch', max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='companies.company')),
            ],
            options={
                'ordering': ['-is_headquarters', 'city'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-followed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_company_follow')],
            },
        ),
    ]
