# Generated by Django 5.2.17 on 2026-09-20 17:12

import core.utils
import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_job_skills_snapshot_and_more'),
        ('companies', '0002_company_benefits_company_business_proof_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyoffice',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='companyoffice',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='companyoffice',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. Chennai Office', max_length=150),
        ),
        migrations.CreateModel(
            name='CompanyProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=300, validators=[core.validators.validate_profile_url])),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('company_products'), validators=[core.validators.validate_image_file])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_services', to='companies.company')),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['company'], name='companies_c_company_9fe123_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('company_review_images'), validators=[core.validators.validate_image_file])),
                ('is_active', models.BooleanField(default=True, help_text='HR can hide a review without editing its content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_review', to='applications.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='companies_c_company_af5a34_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'applicant'), name='unique_review_per_student_per_company')],
            },
        ),
        migrations.CreateModel(
            name='CompanySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('salary_range', models.CharField(help_text='e.g. ₹4 LPA - ₹8 LPA', max_length=100)),
                ('experience_level', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('junior', '0-2 years'), ('mid', '2-5 years'), ('senior', '5-10 years'), ('lead', '10+ years')], max_length=20)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='companies.company')),
            ],
            options={
                'ordering': ['role'],
                'indexes': [models.Index(fields=['company'], name='companies_c_company_ff9a79_idx')],
            },
        ),
    ]
